### ISSUE TITLE
ukf library in ROS project 

### ISSUE THREAD

**Issue by aaramirezd** [sfwa/ukf#35]
Hi, excellent work.

I'm starting with a project in ROS and I'm new with Kalman filters.

Can you compile the library for Ubuntu and work with ROS?

I hope the question does not sound silly, because I cloned the repository and did cmake and make but it just built Eigen3.

Thanks,
Andrés

**Comment by danieldyer** [comment]
Hi Andrés,

Like Eigen3, this is a header-only library, so all you need to do to use it in your project is to add it to your include path. It should compile in Ubuntu using either Clang or GCC 5.x or later.

If you'd like to build the tests to make sure it works with your toolchain, you can build the unit tests with 'make check', or else 'make unittest' and run the resulting 'unittest' executable.

Cheers,
Daniel

**Comment by nightduck** [comment]
Similar issue, but it will not build when used in my own project. see issue #54
