### ISSUE TITLE
Eigen Patch

### ISSUE THREAD

**Issue by lgulich** [sfwa/ukf#53]
Hi there

First, thank you for this great library. I was wondering if you could give some insights on the patch you apply to the Eigen library. Why is this patch not contained in the default Eigen library? Are there any downsides to it? 

Many thanks in advance!

**Comment by LukeAI** [comment]
would also like to hear more...

**Comment by danieldyer** [comment]
The patch is just a one-liner which eliminates a dynamic memory allocation in a situation where it wasn't necessary – this was for a platform I was developing for which didn't support dynamic memory allocation.

The library will compile and run just fine without the patch, but it's necessary if you want to completely avoid dynamic memory allocations (i.e. when using a fixed measurement vector).
