### ISSUE TITLE
square root UKF vs UKF?

### ISSUE THREAD

**Issue by LukeAI** [sfwa/ukf#57]
Thanks for this great lib!

I was interested to hear your take on the square root UKF  - the paper says that it achieves comparable performance to the standard UKF but with less computational cost. In your experience, is that true? If so, is there any advantage to using a standard UKF?

**Comment by danieldyer** [comment]
That’s the claim, but in practice it will probably depend on the structure and dimension of your state and measurement vectors, and also the relative efficiency of the various linear algebra routines in Eigen (QR decomposition, LLT decomposition etc).

For instance, in the benchmarks, the non-square root implementation actually seems to be a little faster in the artificial example I’ve provided, although I haven’t looked in detail into why that is. It’s likely that my implementation of the square-root UKF could be further optimised.

In my experience, the real advantage of the square-root UKF is its considerably improved numerical stability.
